"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Drawer from "@/components/drawer/Drawer";
import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const shouldRenderDrawer = pathname !== "/login"; 
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main className="flex flex-row inter">
          {shouldRenderDrawer && (
          <div className="w-[380px]">
            <Drawer />
          </div>
          )}
          <div className="mt-[75px]">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
