"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Drawer from "@/components/drawer/Drawer";
import { Provider } from "react-redux";
import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });
import { store } from "../store";
import { Toaster } from "@/components/ui/toaster"
import AuthProviders from "@/utils/authProvider";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const shouldRenderDrawer = pathname !== "/";
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <AuthProviders>
            <Navbar />
            <main className="flex flex-row inter">
              {shouldRenderDrawer && (
                <div className="w-[380px]">
                  <Drawer />
                </div>
              )}
              <div className="w-full p-14 mt-[75px]">
                {children}
              </div>
            </main>
            <Toaster />
          </AuthProviders>
        </Provider>
      </body>
    </html>
  );
}
